name: gesture_pattern_detector
description: "gesture_pattern_detector is a Flutter package that allows developers to detect custom gesture patterns, similar to Morse code, in their apps. Define complex gestures by combining taps, long presses, and swipes, and trigger actions when the correct sequence is performed. It's a versatile tool for implementing hidden features or secret gestures, enhancing user interactions in innovative ways."
version: 0.0.1
repository: https://github.com/amaan-0331/gesture_pattern_detector

environment:
  sdk: ">=3.4.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0
